version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/Data:/data
    ports:
      - "80:80"
    command: [nginx, '-g', 'daemon off;']