version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/Data:/data
    ports:
      - 80
    depends_on:
      - web
    command: [nginx, '-g', 'daemon off;']
  web:
    build:
      context: ./
      dockerfile: /pagination-plugin/docker/Dockerfile
    volumes:
      - /mnt/Data:/data